=== CBforeva/CustomSamplers/src/main/java/assignment/assignment.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="assignment">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="payload" />
				<xs:element maxOccurs="unbounded" ref="threads" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="payload">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="threadIDList" />
				<xs:element ref="threadIDRange" />
			</xs:choice>
			<xs:attribute name="name" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="threadIDList" type="xs:string" />

	<xs:element name="threadIDRange">
		<xs:complexType>
			<xs:attribute name="from" use="required" type="xs:integer" />
			<xs:attribute name="to" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>

	<xs:element name="threads">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="payloadList" />
			</xs:sequence>
			<xs:attribute name="idList" />
			<xs:attribute name="idRange" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="payloadList" type="xs:string" />

</xs:schema>

=== CBforeva/CustomSamplers/resources/assignments/example.xml
<?xml version="1.0" encoding="utf-8"?>

<assignment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="assignment.xsd">

	<payload name="rbinary-100.bin">
		<threadIDList> 1 2 40 50 </threadIDList>
		<!-- Can be more: <threadIDList> 10 20 30 40 </threadIDList> -->
	</payload>

	<payload name="rbinary-101.bin">
		<threadIDRange from="20" to="25" />
	</payload>


	<threads idList="1 2 3 4" idRange="6-10">
		<payloadList>
			rbinary-1.bin
			rbinary-2.bin
			rbinary-3.bin
		</payloadList>
	</threads>

	<threads idList="1 5">
		<payloadList> rbinary-10.bin </payloadList>
	</threads>

	<threads idRange="50-55">
		<payloadList> rbinary-10.bin </payloadList>
	</threads>

</assignment>
